In [518]:
# imports
import numpy as np
import random

In [519]:
# nombre de bits a coder
n = 4
# nombre de bits de corrections d'erreur
nC = 3

In [520]:
# base cannonique de matrice a n bits
bases = []
for i in range(n):
    bases.append([1 if j == i else 0 for j in range(n)])
bases = np.array(bases)
print(bases)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [521]:
# endcodage forme : p1, p2, d1, p3, d2, d3 et d4
# p1 => d1, d2, d4
# p2 => d1, d3, d4
# p3 => d2, d3, d4
def hamming7_4(message):
    p1 = 1 if (message[0] + message[1] + message[3]) % 2 == 1 else 0
    p2 = 1 if (message[0] + message[2] + message[3]) % 2 == 1 else 0
    p3 = 1 if (message[1] + message[2] + message[3]) % 2 == 1 else 0
    return [p1, p2, message[0], p3, message[1], message[2], message[3]]

In [522]:
# création de la matrice generatrice
temp = [hamming7_4(base) for base in bases]
G = [[0 for j in range(len(temp))] for i in range(len(temp[0]))]
for i in range(len(temp)):
    for j in range(len(temp[0])):
        G[j][i] = temp[i][j]
G = np.array(G)
print(G)

[[1 1 0 1]
 [1 0 1 1]
 [1 0 0 0]
 [0 1 1 1]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [523]:
# création de la matrice de controle
# on veut 3 bits de corrections d'erreurs donc 3 vecteurs tel que e1, e2 et e3 annulent G
# ainsi on a la matrice suivante
C = np.array([[0, 0, 0, 1, 1, 1, 1], [0, 1, 1, 0, 0, 1, 1], [1, 0, 1, 0, 1, 0, 1]])
print(C)

[[0 0 0 1 1 1 1]
 [0 1 1 0 0 1 1]
 [1 0 1 0 1 0 1]]


In [524]:
# generation d'un message
message = np.array([[random.randint(0, 1)] for i in range(4)])
print(message)

[[1]
 [1]
 [0]
 [1]]


In [525]:
# encodage message
messageHamming = np.dot(G, message)
for i in range(len(messageHamming)):
    messageHamming[i][0] = messageHamming[i][0] % 2
print(messageHamming)

[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]]


In [526]:
# verification d'erreur
verif = np.dot(C, messageHamming.copy())
for i in range(len(verif)):
    verif[i][0] = verif[i][0] % 2
print(verif)

[[0]
 [0]
 [0]]


In [527]:
# ajout d'erreur et modification
indexE = random.randint(0, len(messageHamming) - 1)
messageHamming[indexE][0] = messageHamming[indexE][0] + 1 % 2
print("Erreur insérée au rang {:d}".format(indexE))
# verification d'erreur
verif = np.dot(C, messageHamming.copy())
for i in range(len(verif)):
    verif[i][0] = verif[i][0] % 2
binValue = ""
for x in verif:
    binValue += str(x[0])
indexE = 0
for i in range(len(verif)):
    indexE += 2**(2 - i) if verif[i] else 0
print("Resultat multiplication de la la matrice de controle et du message ( en binaire ) {:s} => {:d} (position de l'erreur)".format(binValue, indexE - 1))

Erreur insérée au rang 0
Resultat multiplication de la la matrice de controle et du message ( en binaire ) 001 => 0 (position de l'erreur)
