In [64]:
# imports
import random
import numpy as np

In [75]:
# generation du message
message = [random.randint(0, 1) for i in range(4)]
print(np.array([message[i] for i in range(len(message))]))
print("taille : {:d}".format(len(message)))

[0 0 1 0]
taille : 4


In [66]:
# fonctions utiles
def is_prime(num):
    if num == 0 or num == 1:
        return False
    for x in range(2, num):
        if num % x == 0:
            return False
    else:
        return True

def generatePrimeAbove(n):
    n += 1
    while (not is_prime(n)):
        n+=1
    return n

# definition de la taille du message de reedSolomon
size = generatePrimeAbove(len(message) + 1)
print(size)

7


In [67]:
# generation du polynome generateur
class Polynome:
    def __init__(self, degrees):
        degrees.sort()
        self.degrees = degrees.copy()
    def getMaxDegree(self):
        return self.degrees[-1][1]
    def getValueDegree(self, n):
        for i in range(len(self.degrees)):
            if (i > len(self.degrees) - 1) :
                return 0
            elif (n == self.degrees[i][1]) :
                return self.degrees[i][0]
        return 0
    def getDegrees(self):
        d = []
        for i in range(self.getMaxDegree() + 1):
            d.append(self.getValueDegree(i))
        return d
    def __repr__(self):
        s = "Polynome "
        first = True
        for d in self.degrees:
            if (first):
                first = not first
            else :
                s += " + "
            s += (str(d[0]) if d[0] != 1 else "") + "x^" + str(d[1])
        return s

g = Polynome([(1, 0), (1, 1), (1, 3)])

print(g)
print(g.getDegrees())

Polynome x^0 + x^1 + x^3
[1, 1, 0, 1]


In [68]:
# generation matrice generatrice
G = []
for i in range(len(message)):
    G.append([])
    for j in range(size - g.getMaxDegree()):
        if (i == j):
            for bit in g.getDegrees():
                G[i].append(bit)
        else :
            G[i].append(0)
G = np.array(G)
print(G)

[[1 1 0 1 0 0 0]
 [0 1 1 0 1 0 0]
 [0 0 1 1 0 1 0]
 [0 0 0 1 1 0 1]]


In [71]:
# encodeage
encoded = np.dot(G, np.array([message[i] for i in range(len(message))]))
print(encoded)

ValueError: shapes (4,7) and (4,) not aligned: 7 (dim 1) != 4 (dim 0)